<?php
// This script and data application were generated by AppGini 22.14
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/bypass.php');
	include_once(__DIR__ . '/bypass_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('bypass');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'bypass';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`bypass`.`id`" => "id",
		"`bypass`.`invoice_no`" => "invoice_no",
		"`bypass`.`amount`" => "amount",
		"`bypass`.`master_status`" => "master_status",
		"`bypass`.`regular_status`" => "regular_status",
		"`bypass`.`track`" => "track",
		"`bypass`.`note`" => "note",
		"`bypass`.`timestamp`" => "timestamp",
		"`bypass`.`client`" => "client",
		"`bypass`.`ref`" => "ref",
		"`bypass`.`route`" => "route",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`bypass`.`id`',
		2 => 2,
		3 => 3,
		4 => 4,
		5 => 5,
		6 => 6,
		7 => 7,
		8 => 8,
		9 => '`bypass`.`client`',
		10 => 10,
		11 => 11,
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`bypass`.`id`" => "id",
		"`bypass`.`invoice_no`" => "invoice_no",
		"`bypass`.`amount`" => "amount",
		"`bypass`.`master_status`" => "master_status",
		"`bypass`.`regular_status`" => "regular_status",
		"`bypass`.`track`" => "track",
		"`bypass`.`note`" => "note",
		"`bypass`.`timestamp`" => "timestamp",
		"`bypass`.`client`" => "client",
		"`bypass`.`ref`" => "ref",
		"`bypass`.`route`" => "route",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`bypass`.`id`" => "Id",
		"`bypass`.`invoice_no`" => "Invoice_no",
		"`bypass`.`amount`" => "Amount",
		"`bypass`.`master_status`" => "Master_status",
		"`bypass`.`regular_status`" => "Regular_status",
		"`bypass`.`track`" => "Track",
		"`bypass`.`note`" => "Note",
		"`bypass`.`timestamp`" => "Timestamp",
		"`bypass`.`client`" => "Client",
		"`bypass`.`ref`" => "Ref",
		"`bypass`.`route`" => "Route",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`bypass`.`id`" => "id",
		"`bypass`.`invoice_no`" => "invoice_no",
		"`bypass`.`amount`" => "amount",
		"`bypass`.`master_status`" => "master_status",
		"`bypass`.`regular_status`" => "regular_status",
		"`bypass`.`track`" => "track",
		"`bypass`.`note`" => "note",
		"`bypass`.`timestamp`" => "timestamp",
		"`bypass`.`client`" => "client",
		"`bypass`.`ref`" => "ref",
		"`bypass`.`route`" => "route",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = [];

	$x->QueryFrom = "`bypass` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 1;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'bypass_view.php';
	$x->TableTitle = 'Bypass';
	$x->TableIcon = 'resources/table_icons/table.png';
	$x->PrimaryKey = '`bypass`.`id`';

	$x->ColWidth = [150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, ];
	$x->ColCaption = ['Id', 'Invoice_no', 'Amount', 'Master_status', 'Regular_status', 'Track', 'Note', 'Timestamp', 'Client', 'Ref', 'Route', ];
	$x->ColFieldName = ['id', 'invoice_no', 'amount', 'master_status', 'regular_status', 'track', 'note', 'timestamp', 'client', 'ref', 'route', ];
	$x->ColNumber  = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/bypass_templateTV.html';
	$x->SelectedTemplate = 'templates/bypass_templateTVS.html';
	$x->TemplateDV = 'templates/bypass_templateDV.html';
	$x->TemplateDVP = 'templates/bypass_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: bypass_init
	$render = true;
	if(function_exists('bypass_init')) {
		$args = [];
		$render = bypass_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: bypass_header
	$headerCode = '';
	if(function_exists('bypass_header')) {
		$args = [];
		$headerCode = bypass_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: bypass_footer
	$footerCode = '';
	if(function_exists('bypass_footer')) {
		$args = [];
		$footerCode = bypass_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
