<?php
// This script and data application were generated by AppGini 22.14
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/math.php');
	include_once(__DIR__ . '/math_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('math');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'math';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`math`.`id`" => "id",
		"`math`.`created_at`" => "created_at",
		"IF(    CHAR_LENGTH(`clients1`.`name`), CONCAT_WS('',   `clients1`.`name`), '') /* Client */" => "client",
		"`math`.`perc`" => "perc",
		"`math`.`abbr`" => "abbr",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`math`.`id`',
		2 => '`math`.`created_at`',
		3 => '`clients1`.`name`',
		4 => 4,
		5 => 5,
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`math`.`id`" => "id",
		"`math`.`created_at`" => "created_at",
		"IF(    CHAR_LENGTH(`clients1`.`name`), CONCAT_WS('',   `clients1`.`name`), '') /* Client */" => "client",
		"`math`.`perc`" => "perc",
		"`math`.`abbr`" => "abbr",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`math`.`id`" => "Id",
		"`math`.`created_at`" => "Created_at",
		"IF(    CHAR_LENGTH(`clients1`.`name`), CONCAT_WS('',   `clients1`.`name`), '') /* Client */" => "Client",
		"`math`.`perc`" => "Perc",
		"`math`.`abbr`" => "Abbr",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`math`.`id`" => "id",
		"`math`.`created_at`" => "created_at",
		"IF(    CHAR_LENGTH(`clients1`.`name`), CONCAT_WS('',   `clients1`.`name`), '') /* Client */" => "client",
		"`math`.`perc`" => "perc",
		"`math`.`abbr`" => "abbr",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = ['client' => 'Client', ];

	$x->QueryFrom = "`math` LEFT JOIN `clients` as clients1 ON `clients1`.`id`=`math`.`client` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 1;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'math_view.php';
	$x->TableTitle = 'Math';
	$x->TableIcon = 'resources/table_icons/table.png';
	$x->PrimaryKey = '`math`.`id`';

	$x->ColWidth = [150, 150, 150, 150, 150, ];
	$x->ColCaption = ['Id', 'Created_at', 'Client', 'Perc', 'Abbr', ];
	$x->ColFieldName = ['id', 'created_at', 'client', 'perc', 'abbr', ];
	$x->ColNumber  = [1, 2, 3, 4, 5, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/math_templateTV.html';
	$x->SelectedTemplate = 'templates/math_templateTVS.html';
	$x->TemplateDV = 'templates/math_templateDV.html';
	$x->TemplateDVP = 'templates/math_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: math_init
	$render = true;
	if(function_exists('math_init')) {
		$args = [];
		$render = math_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: math_header
	$headerCode = '';
	if(function_exists('math_header')) {
		$args = [];
		$headerCode = math_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: math_footer
	$footerCode = '';
	if(function_exists('math_footer')) {
		$args = [];
		$footerCode = math_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
