<?php
// This script and data application were generated by AppGini 22.14
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/token.php');
	include_once(__DIR__ . '/token_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('token');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'token';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`token`.`id`" => "id",
		"`token`.`name`" => "name",
		"`token`.`cid`" => "cid",
		"`token`.`token`" => "token",
		"`token`.`timestamp`" => "timestamp",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`token`.`id`',
		2 => 2,
		3 => 3,
		4 => 4,
		5 => 5,
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`token`.`id`" => "id",
		"`token`.`name`" => "name",
		"`token`.`cid`" => "cid",
		"`token`.`token`" => "token",
		"`token`.`timestamp`" => "timestamp",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`token`.`id`" => "Id",
		"`token`.`name`" => "Name",
		"`token`.`cid`" => "Cid",
		"`token`.`token`" => "Token",
		"`token`.`timestamp`" => "Timestamp",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`token`.`id`" => "id",
		"`token`.`name`" => "name",
		"`token`.`cid`" => "cid",
		"`token`.`token`" => "token",
		"`token`.`timestamp`" => "timestamp",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = [];

	$x->QueryFrom = "`token` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 1;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'token_view.php';
	$x->TableTitle = 'Token';
	$x->TableIcon = 'resources/table_icons/table.png';
	$x->PrimaryKey = '`token`.`id`';

	$x->ColWidth = [150, 150, 150, 150, 150, ];
	$x->ColCaption = ['Id', 'Name', 'Cid', 'Token', 'Timestamp', ];
	$x->ColFieldName = ['id', 'name', 'cid', 'token', 'timestamp', ];
	$x->ColNumber  = [1, 2, 3, 4, 5, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/token_templateTV.html';
	$x->SelectedTemplate = 'templates/token_templateTVS.html';
	$x->TemplateDV = 'templates/token_templateDV.html';
	$x->TemplateDVP = 'templates/token_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: token_init
	$render = true;
	if(function_exists('token_init')) {
		$args = [];
		$render = token_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: token_header
	$headerCode = '';
	if(function_exists('token_header')) {
		$args = [];
		$headerCode = token_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: token_footer
	$footerCode = '';
	if(function_exists('token_footer')) {
		$args = [];
		$footerCode = token_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
